### ISSUE TITLE
weewx.UnknownType: outEquiTemp.max_ge: unknown aggregation type

### ISSUE THREAD

**Issue by hoetzgit** [roe-dl/weewx-GTS#28]
Hallo,

weiß nicht, ob es an meiner Konfiguration liegt, aber mit aktueller GTS Version erscheint bei mir folgender Fehler (WeeWX 4.10.2):

```
Feb 27 16:00:33 weewx weewx[105352] ERROR weewx.reportengine:         ****  outEquiTemp.max_ge: outEquiTemp.max_ge: unknown aggregation type
Feb 27 16:00:33 weewx weewx[105352] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Feb 27 16:00:33 weewx weewx[105352] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/GTS.py", line 1006, in calc_derived
Feb 27 16:00:33 weewx weewx[105352] ERROR weewx.reportengine:         ****      elif aggregate_type=='avg':
Feb 27 16:00:33 weewx weewx[105352] ERROR weewx.reportengine:         ****  weewx.UnknownType: outEquiTemp.max_ge: unknown aggregation type
```

Grüße
Henry

**Comment by roe-dl** [comment]
Bitte mal in der genannten Zeile 1006 `weewx.UnknownType` durch `weewx.UnknownAggregation` zu ersetzen. Löst das das Problem?

Hintergrund: Während diese Erweiterung früher **nach** den originalen WeeWX-Routinen eingeordnet war, ist sie jetzt **davor** einsortiert, um die Funktion `weewx.xtypes.XTypeTable.get_aggregate()` in WeeWX 5.0 überschreiben zu können. Das ist offenbar nicht ohne Nebenwirkungen geblieben.

**Comment by roe-dl** [comment]
Die Fehlermeldung ist nach der Änderung unter Version 4.10 weg. Bei mir kam beim Test mit `$year.outEquiTemp.max_ge((20,'degree_C','group_temperature'))` aber keine Zahl.

**Comment by hoetzgit** [comment]
> Die Fehlermeldung ist nach der Änderung unter Version 4.10 weg. 

bei mir jetzt auch. Mehr habe ich noch nicht geprüft.

**Comment by roe-dl** [comment]
Wenn die Größe in die Datenbank gespeichert wird, dann funktioniert `max_ge`, anderenfalls nicht. Das dürfte auch früher schon so gewesen sein. Insoweit ist letzteres nicht Gegenstand dieses Issues. `max_ge` funktioniert jetzt wieder für Größen aus der Datenbank. Das Problem sollte damit gelöst sein.

**Summary in English:**

People using WeeWX 5.0 reported excessive report creation duration due to the new function `weewx.xtypes.XTypeTable.get_aggregate`. See issue #27 for details. The fix to that problem involved prepending this extension to the XTypes list instead of appending it. This way the `get_aggregate()` function of this extension gets called instead of that of the DailySummeries class even if the observation type is available in the database and the aggregation could be retrieved from there. This resulted in the error messages described in this issue. So another fix was required, now inserting this extension after DailySummaries (which handles aggregations of observation types available in the database) but before XTypeTable (which in WeeWX 5.0 handles aggregations of XTypes that do not handle their aggregations themselves).

**Comment by roe-dl** [comment]
Nachdem der letzte Beitrag jetzt eine Woche zurückliegt, mache ich dieses Issue zu.
